add example, swap video for 'list frame'

diff --git a/converters/thorn-to-gif b/converters/thorn-to-gif
--- a/converters/thorn-to-gif
+++ b/converters/thorn-to-gif
@@ -1,50 +1,67 @@
 #! /bin/sh
 
 set -e
+FONT_DIR="$HOME/.local/share/thorn/fonts/"
+FONT='ibm_9x14'
+FPS=5
 
-font='ibm_9x14'
-fps=5
+print_help() {
+    printf 'thorn-to-gif options:
+        --font-dir DIR       Set the font directory to DIR
+        --font-name NAME     Set the font to NAME
+        --fps FPS            Set the fps to FPS
+        --help               Show this help message
+    '
+    exit 1
+}
 
 while [ $# != 0 ]; do
     case "$1" in 
-        --font)
-            font="$2"
+        --font-dir)
+            FONT_DIR="$2"
+            shift
+            ;;
+        --font-name)
+            FONT="$2"
             shift
             ;;
         --fps)
-            fps="$2"
+            FPS="$2"
             shift
             ;;
+        --help | -h)
+            print_help
+            ;;
         *)
-            printf '
-thorn-to-gif options:
-
-    \33[91m--font \33[0mFONT     set the font to ~/.local/share/thorn/fonts/FONT
-    \33[91m--fps  \33[0mFPS      set the fps to FPS
-    \33[91m--help \33[0m         show this help message
-
-'
+            printf "\33[91merror: \33[0munknown option '%s'\n" "$1"
+            printf 'use --help to see all options\n'
             exit 1
             ;;
     esac
     shift
 done
 
-echo $font
-echo $fps
+FONT_PATH="$FONT_DIR/$FONT"
 
-thorn-to-ppm --font $font
+printf "    \033[95mfont-dir   \033[0m$FONT_DIR\n" >&2
+printf "    \033[95mfont-name  \033[0m$FONT\n"     >&2
+printf "    \033[95mfps        \033[0m$FPS\n"      >&2
 
-mkdir ppms || true
+thorn-to-ppm --font $FONT_PATH
+
+mkdir -p ppms
 mv *.ppm ppms
 
-ffmpeg -i ppms/output%05d.ppm -vf palettegen=max_colors=8 palette.png
+ffmpeg -loglevel error -i ppms/output%05d.ppm -vf palettegen=max_colors=8 palette.png
+
 ffmpeg                                    \
-    -framerate $fps                       \
+    -loglevel error                       \
+    -framerate $FPS                       \
     -i ppms/output%05d.ppm                \
     -i palette.png                        \
     -lavfi "paletteuse=dither=none"       \
-    output.gif 
+    -f gif                                \
+    -
 
 rm -r ppms palette.png 
 
